# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "364ad467aa5c16c45766685611d1ae54"
name = "bc-design-app-embed"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions"

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

[metaobjects.app.navigation_config]
name = "Navigation configuration"
display_name_field = "title"

  [metaobjects.app.navigation_config.access]
  admin = "merchant_read_write"

[metaobjects.app.navigation_config.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.navigation_config.fields.menu_handle]
name = "Menu handle"
type = "single_line_text_field"

[metaobjects.app.banner_config]
name = "Banner configuration"
display_name_field = "title"

  [metaobjects.app.banner_config.access]
  admin = "merchant_read_write"

[metaobjects.app.banner_config.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.banner_config.fields.slides]
name = "Slides"
type = "list.metaobject_reference<$app:banner_slide>"

[metaobjects.app.banner_slide]
name = "Banner slide"
display_name_field = "title"

  [metaobjects.app.banner_slide.access]
  admin = "merchant_read_write"

[metaobjects.app.banner_slide.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.banner_slide.fields.desktop_image]
name = "Desktop image"
type = "file_reference"

[metaobjects.app.banner_slide.fields.video]
name = "Shopify-hosted video"
type = "file_reference"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
